---
title: "2004 Demographics"
author: "Paige Kemp"
Date: "`r Sys.Date()`"
output: html_document
---
```{r clear environment, warning=FALSE}
rm(list=ls())
```

```{r load packages}
# Load packages
pacman::p_load("tidyverse", "magrittr", "janitor")
```

```{r read data}
# Experiment 1
demo_data_exp1 <- 
  read.csv("../Data/Exp1/2004.1_demographics.csv", stringsAsFactors = FALSE, fileEncoding = "UTF-8-BOM")

# Experiment 2
demo_data_exp2 <- 
  read.csv("../Data/Exp2/2004.2_demographics.csv", stringsAsFactors = FALSE, fileEncoding = "UTF-8-BOM")
```

```{r clean variable names}
# Experiment 1
demo_data_exp1 %<>% clean_names()
demo_data_exp1 <- demo_data_exp1 %>% mutate_if(is.character, str_to_lower)

# Experiment 2
demo_data_exp2 %<>% clean_names()
demo_data_exp2 <- demo_data_exp2 %>% mutate_if(is.character, str_to_lower)
```

```{r sample size, echo = FALSE, message = FALSE}
# Experiment 1
demo_data_exp1_n <- 
  demo_data_exp1 %>% group_by(age_group) %>% mutate(N = n_distinct(subject)) %>% summarise(n = mean(N))

# Experiment 2
demo_data_exp2_n <- 
  demo_data_exp2 %>% group_by(age_group) %>% mutate(N = n_distinct(subject)) %>% summarise(n = mean(N))
```

```{r demographics}
# Experiment 1
(age_gender_e1_df <- demo_data_exp1 %>%
    group_by(age_group) %>%
  dplyr::summarize(subject_n = n(),
            females = sum(sex == "female"),
            male = sum(sex == "male"),
            mean_age = mean(age),
            SD_age = sd(age),
            min_age = min(age),
            max_age = max(age)) %>% 
  mutate_if(is.numeric, round, digits = 2))

# Experiment 2
(age_gender_e2_df <- demo_data_exp2 %>%
    group_by(age_group) %>%
  dplyr::summarize(subject_n = n(),
            females = sum(sex_response == "female"),
            male = sum(sex_response == "male"),
            gender_diverse = sum(sex_response == "gender diverse"),
            mean_age = mean(age_response),
            SD_age = sd(age_response),
            min_age = min(age_response),
            max_age = max(age_response)) %>% 
  mutate_if(is.numeric, round, digits = 2))
```


